# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
# remote_theme: pages-themes/cayman@v0.2.0
remote_theme: zendesk/jekyll-theme-zendesk-garden@main
plugins:
- jekyll-remote-theme
title: Houssem Dellai videos
description: Learn about Azure, Kubernetes, Terraform and DevOps
show_downloads: false # ["true" or "false" (unquoted) to indicate whether to provide a download URL]
# google_analytics: [Your Google Analytics tracking ID]

sidebar:
  - getting-started
